# Generated by Django 4.1.5 on 2023-03-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iphonemenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(max_length=256, null=True, verbose_name='описание')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер')),
                ('imgcolor', models.ImageField(null=True, upload_to='img')),
                ('imgcolor2', models.ImageField(null=True, upload_to='img')),
                ('imgcolor3', models.ImageField(null=True, upload_to='img')),
                ('imgcolor4', models.ImageField(null=True, upload_to='img')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню часов',
            },
        ),
        migrations.RemoveField(
            model_name='iphone',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='iphone',
            name='photo3',
        ),
    ]
