# Generated by Django 4.1.5 on 2023-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_iphonemenu_options_remove_iphonemenu_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphonemenu',
            name='imgcolor5',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='iphonemenu',
            name='sim',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SIM'),
        ),
        migrations.AlterField(
            model_name='iphonemenu',
            name='sim2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SIM2'),
        ),
        migrations.AlterField(
            model_name='iphonemenu',
            name='sim3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SIM3'),
        ),
        migrations.AlterField(
            model_name='iphonemenu',
            name='size2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Емкость2'),
        ),
        migrations.AlterField(
            model_name='iphonemenu',
            name='size3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Емкость3'),
        ),
        migrations.AlterField(
            model_name='iphonemenu',
            name='size4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Емкость4'),
        ),
    ]
