# Generated by Django 4.1.5 on 2023-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_iphonemenu_imgcolor5_alter_iphonemenu_sim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphonemenu',
            name='list',
            field=models.TextField(max_length=256, null=True, verbose_name='Описание продукта'),
        ),
    ]
