# Generated by Django 4.1.5 on 2023-03-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_iphonemenu_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphonemenu',
            name='photoiphone',
            field=models.ImageField(null=True, upload_to='img', verbose_name='aaadsss'),
        ),
    ]
