# Generated by Django 4.1.5 on 2023-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_iphonemenu_photoiphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphonemenu',
            name='list',
            field=models.TextField(max_length=656, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='iphonemenu',
            name='photoiphone',
            field=models.ImageField(null=True, upload_to='img', verbose_name='фото Айфона'),
        ),
    ]
