# Generated by Django 4.1.5 on 2023-03-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_iphonemenu_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphonemenu',
            name='list',
            field=models.TextField(max_length=2706, null=True, verbose_name='Описание продукта'),
        ),
    ]
