# Generated by Django 4.1.5 on 2023-03-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_img_menuwatch_imgcolor2_menuwatch_imgcolor3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuwatch',
            name='list',
            field=models.TextField(max_length=5706, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='menuwatch',
            name='photoiphone',
            field=models.ImageField(null=True, upload_to='img', verbose_name='фото часов'),
        ),
    ]
