# Generated by Django 4.1.5 on 2023-03-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_menuwatch_list_alter_menuwatch_photoiphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuwatch',
            old_name='photoiphone',
            new_name='photowatch',
        ),
    ]
