# Generated by Django 4.1.5 on 2023-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_photoiphone_menuwatch_photowatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuwatch',
            name='imgcolor10',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
