# Generated by Django 4.1.5 on 2023-03-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_iphonemenu_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iphonemenu',
        ),
    ]
