# Generated by Django 4.1.5 on 2023-03-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_iphonemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='akustika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(null=True, verbose_name='Цена товара')),
                ('photo', models.FileField(blank=True, null=True, upload_to='img')),
            ],
            options={
                'verbose_name': 'Акустика',
                'verbose_name_plural': 'Акустик',
            },
        ),
        migrations.AlterField(
            model_name='iphone',
            name='content',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='imgcolor2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='imgcolor3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='imgcolor4',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='imgcolor5',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='list',
            field=models.TextField(blank=True, max_length=2706, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='size2',
            field=models.CharField(max_length=20, null=True, verbose_name='Емкость2'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='size3',
            field=models.CharField(max_length=20, null=True, verbose_name='Емкость3'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='size4',
            field=models.CharField(max_length=20, null=True, verbose_name='Емкость4'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
