# Generated by Django 4.1.5 on 2023-04-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_phonemain'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text2', models.TextField(verbose_name='текст жирный')),
                ('text3', models.TextField(verbose_name='текст обычный')),
                ('text4', models.TextField(verbose_name='текст обычный')),
                ('text5', models.TextField(verbose_name='текст жирный')),
                ('text6', models.TextField(verbose_name='текст обычный')),
                ('text7', models.TextField(verbose_name='текст обычный')),
                ('text8', models.TextField(verbose_name='текст обычный')),
                ('text9', models.TextField(verbose_name='текст обычный')),
                ('text10', models.TextField(verbose_name='текст обычный')),
                ('text1', models.TextField(verbose_name='текст обычный')),
                ('text12', models.TextField(verbose_name='текст обычный')),
                ('text13', models.TextField(verbose_name='текст обычный')),
                ('text14', models.TextField(verbose_name='текст обычный')),
                ('text15', models.TextField(verbose_name='текст жирный')),
                ('text16', models.TextField(verbose_name='текст обычный')),
                ('text17', models.TextField(verbose_name='текст обычный')),
                ('text18', models.TextField(verbose_name='текст обычный')),
                ('text19', models.TextField(verbose_name='текст обычный')),
                ('text20', models.TextField(verbose_name='текст обычный')),
            ],
            options={
                'verbose_name': 'главная текст футер',
                'verbose_name_plural': 'главные текста футера',
            },
        ),
    ]
