# Generated by Django 4.1.7 on 2023-04-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_maintext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintext',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text12',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text13',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text14',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text15',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text16',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text17',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text18',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text19',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text20',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text6',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text7',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text8',
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='text9',
        ),
    ]
