# Generated by Django 4.1.7 on 2023-04-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_maintext_text10_remove_maintext_text12_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='maintext',
            new_name='maintextadmin',
        ),
    ]
