# Generated by Django 4.1.5 on 2023-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_maintextadmin_text1'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text0', models.TextField(max_length=1000)),
                ('text1', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'маки',
                'verbose_name_plural': 'мак',
            },
        ),
        migrations.DeleteModel(
            name='maintextadmin',
        ),
    ]
