# Generated by Django 4.1.5 on 2023-04-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_maintext_delete_maintextadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintext',
            options={'verbose_name': 'главный текста', 'verbose_name_plural': 'главные тескт'},
        ),
        migrations.AddField(
            model_name='maintext',
            name='text10',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text11',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text12',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text13',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text14',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст жирный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text15',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text16',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text17',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text18',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text19',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text2',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text3',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст жирный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text6',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text7',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text8',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text9',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст обычный'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Названиеи'),
        ),
        migrations.AlterField(
            model_name='maintext',
            name='text0',
            field=models.TextField(verbose_name='текст обычный'),
        ),
        migrations.AlterField(
            model_name='maintext',
            name='text1',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='текст жирный'),
        ),
    ]
