# Generated by Django 4.1.7 on 2023-04-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_maintext_options_maintext_text10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.TextField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('number', models.TextField(blank=True, max_length=20, null=True, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'главная смартфон',
                'verbose_name_plural': 'главные смартфоны',
            },
        ),
    ]
