# Generated by Django 4.1.7 on 2023-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'юзеры', 'verbose_name_plural': 'юзеры'},
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(max_length=20, null=True, verbose_name='фамилия'),
        ),
    ]
