# Generated by Django 4.1.5 on 2023-04-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_users_options_alter_users_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
