# Generated by Django 4.1.7 on 2023-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, null=True, verbose_name='фамилия')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'юзеры',
                'verbose_name_plural': 'юзеры',
            },
        ),
    ]
