# Generated by Django 4.1.7 on 2023-04-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Номер'),
        ),
    ]
