# Generated by Django 4.1.5 on 2023-04-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'юзер', 'verbose_name_plural': 'юзеры'},
        ),
    ]
