# Generated by Django 4.1.7 on 2023-04-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_remove_bot_content_bot_name_bot_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='time_update',
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
